name: GPU Cloud Security Lab CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml nvidia-ml-py3 PyPDF2 boto3 requests || true

    - name: Run CIS Dockerfile scanner
      run: python cis-scanner/cis_docker_check.py || true

    - name: Run Kubernetes hardening checker
      run: python tools/k8s_hardening_check.py || true

    - name: Run CUDA memory check (best-effort)
      run: python cuda-research/cuda-memory-check.py || true
